# Generated by Django 6.0.3 on 2026-06-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.CharField(choices=[('morning', 'Morning (9 AM – 11 AM)'), ('afternoon', 'Afternoon (12 PM – 3 PM)'), ('evening', 'Evening (4 PM – 6 PM)')], default='morning', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='wash.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
